fix: file upload size limit and API error response
ZipThought/llassist pull request #7
Opened 2024-11-25 09:36 UTC by milmigi

This pull request includes several changes to improve error handling, file upload functionality, and configuration management across different parts of the application. The most important changes include updating error responses, adding file upload settings, and improving file validation and upload processes.

Error handling improvements:

* [`llassist.ApiService/Program.cs`](diffhunk://#diff-40818100b5106996df3cd89724d4b97d5952ef96ec982bf947a950acb2b4db28L98-R110): Replaced `ProblemDetails` with `ApiErrorResponse` for more detailed error responses and changed the content type to `application/json`.

File upload functionality:

* [`llassist.Common/Models/Configuration/FileUploadSettings.cs`](diffhunk://#diff-fd79ee51857d06c13b96f174a832bdee67770f60473e721601235ed3ef77a373R1-R8): Added a new configuration class for file upload settings, including maximum size and allowed extensions.
* [`llassist.Web/Components/Pages/Projects/ProjectList.razor`](diffhunk://#diff-dbda77b09957a8aef16caa4c439ae1882799f27f8e907b61b6b5d68df6e85830L65-R75): Integrated file upload settings into the UI, added validation for file uploads, and improved error handling during the upload process. [[1]](diffhunk://#diff-dbda77b09957a8aef16caa4c439ae1882799f27f8e907b61b6b5d68df6e85830L65-R75) [[2]](diffhunk://#diff-dbda77b09957a8aef16caa4c439ae1882799f27f8e907b61b6b5d68df6e85830R226-R228) [[3]](diffhunk://#diff-dbda77b09957a8aef16caa4c439ae1882799f27f8e907b61b6b5d68df6e85830L281-R363)

Configuration management:

* [`llassist.Web/Program.cs`](diffhunk://#diff-b83a8fd55b5bd4050174343a79e16880021c7d85a475c7a213e885d76c631947R20-R28): Configured the application to use the new file upload settings from the configuration file and adjusted the maximum file size for uploads.
* [`llassist.Web/appsettings.json`](diffhunk://#diff-716a83384c4c18832ee6428b06bdfdeeec92f416b6c5524a2e7293bc7578f2fcL8-R12): Added new configuration settings for file uploads, including maximum size and allowed extensions.

2024-11-25 12:18 UTC, cyharyanto reviewed
What do you think about where to put the checking? Should it be part of the ApiService instead of the Web?

Overall:

**ApiService:**
👍 Uses clean error response model (`ApiErrorResponse`) with timestamp and details
❓ No file validation implementation yet in the backend

**Web:**
👍 Multiple validation layers:
  - Frontend checks (`IsValidUpload` method) before upload starts
  - Settings injected via DI (`FileUploadSettings`)
  - Visual feedback (`uploadError`, `isUploading states`)
  - Max size enforced at stream level (`OpenReadStream` with `maxAllowedSize`)

❓ Yet, duplicate configuration needed in both `FormOptions` and `FileUploadSettings`

**Both Components:**
👍 Central configuration via `appsettings.json`
👍 Type-safe settings via `FileUploadSettings` class
❓ Risk of mismatched validation rules if not kept in sync

**Recommendations:**
👍 Common, reusable checking code in `llassist.Common`
👍 `ApiService` to load the configuration, not `Web`
👍 Can consider to use the in-database configuration too

2024-11-25 22:28 UTC, milmigi commented
@cyharyanto both layer should have the checking, since we need to explicitly increase the file read stream and server-side frontend also need to be protected. We can move the configuration to backend and open an API for the frontend to retrieve and do validation.

2024-11-27 22:30 UTC, cyharyanto commented on llassist.ApiService/Services/FileUploadSettingsService.cs
> +    }
TBH, I think having a specialized service just for `FileUploadSettings` is a bit too scoped.

2024-11-27 22:32 UTC, cyharyanto requested changes

2024-11-27 22:32 UTC, cyharyanto commented on llassist.ApiService/Controllers/FileUploadSettingsController.cs
> +}
I think it is much better just to use the common app settings. I imagine the file upload settings can eventually be configured on the database level.

2024-11-28 04:11 UTC, milmigi commented on llassist.ApiService/Services/FileUploadSettingsService.cs
> +    }
updated

2024-11-28 04:11 UTC, milmigi commented on llassist.ApiService/Controllers/FileUploadSettingsController.cs
> +}
as discusses, as of now we're still using common app settings. once we introduce user / owner / tenant, then we have room to configure this settings according to the new hierarchy

2024-11-30 10:25 UTC, cyharyanto approved these changes
Thank you! I think it is much better as in not introducing long-term issue.

2024-12-01 02:46 UTC, merged